services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: schdusr
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scheduler
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "schdusr", "-d", "scheduler"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    # Install AWS CLI on container startup
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y curl unzip miller &&
      curl 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip' -o 'awscliv2.zip' &&
      unzip -o awscliv2.zip &&
      ./aws/install &&
      rm -rf awscliv2.zip aws &&
      docker-entrypoint.sh postgres
      "
    networks:
      - app-network

  flyway:
    image: flyway/flyway:10-alpine
    container_name: sched_flyway2
    depends_on:
      - postgres
    volumes:
      - ./migrations/sql:/flyway/sql:ro
    command: >
      -url=jdbc:postgresql://postgres:5432/scheduler
      -user=schdusr
      -password=password
      -schemas=org_fifth_st
      -locations=filesystem:/flyway/migrations,filesystem:/flyway/testdata
      -createSchemas=true
      -connectRetries=10
      -connectRetriesInterval=5
      migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/scheduler
      FLYWAY_USER: schdusr
      FLYWAY_PASSWORD: password
      FLYWAY_BASELINE_ON_MIGRATE: true
    networks:
      - app-network

  flyway2:
    image: flyway/flyway:10-alpine
    container_name: sched_flyway
    depends_on:
      - postgres
    volumes:
      - ./migrations/sql:/flyway/sql:ro
    command: >
      -url=jdbc:postgresql://postgres:5432/scheduler
      -user=schdusr
      -password=password
      -schemas=org_green_dragon
      -locations=filesystem:/flyway/migrations,filesystem:/flyway/testdata
      -createSchemas=true
      -connectRetries=10
      -connectRetriesInterval=5
      migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/scheduler
      FLYWAY_USER: schdusr
      FLYWAY_PASSWORD: password
      FLYWAY_BASELINE_ON_MIGRATE: true
    networks:
      - app-network

  keycloak:
    build:
      context: ./keycloak-config
      dockerfile: Dockerfile
    container_name: keycloak_sched
    command: start-dev --import-realm --config-file=/opt/keycloak/conf/keycloak.conf
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/scheduler
      KC_DB_USERNAME: schdusr
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: keycloak
      KC_HTTP_ENABLED: true
      KC_HTTPS_PORT: -1
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_SSL_REQUIRED: none
      KC_IMPORT_REALM: /opt/keycloak/data/import/realm-export.json
    volumes:
      - ./keycloak-config/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
      - ./keycloak-config/themes/:/opt/keycloak/themes/:ro
      - ./keycloak-config/keycloak.dev.conf:/opt/keycloak/conf/keycloak.conf:ro
    ports:
      - "8080:8080"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    container_name: backend
    # entrypoint: sh -c "npm i && npm run start:dev"
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_USER: schdusr
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: scheduler
    # image: node:22
    ports: ["3001:3000"]
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api",
        ]
    working_dir: "/app"
    volumes:
      - ./backend/data:/app/data

  frontend:
    container_name: frontend
    entrypoint: sh -c "npm ci && npm run dev"
    environment:
      BACKEND_URL: http://backend:3000
      PORT: 3000
      NODE_ENV: development
    image: node:22
    ports: ["3000:3000"]
    volumes: ["./frontend:/app", "/app/node_modules"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    working_dir: "/app"
    depends_on:
      backend:
        condition: service_healthy

  caddy:
    container_name: caddy
    profiles: ["caddy"]
    build: ./frontend
    environment:
      NODE_ENV: development
      PORT: 3000
      BACKEND_URL: http://backend:3000
      LOG_LEVEL: info
    ports: ["3005:3000"]
    volumes: ["./frontend/Caddyfile:/etc/caddy/Caddyfile"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    depends_on:
      backend:
        condition: service_healthy

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
