export enum SearchAttr {
  LocationType = "locationType",
  LocationName = "locationName",
  LocationId = "locationId",
  LocationGroup = "locationGroup",
  PermitNo = "permitNumber",
  Media = "media",
  ObservedProperty = "observedProperty",
  WorkedOrderNo = "workedOrderNo",
  SamplingAgency = "samplingAgency",
  AnalyzingAgency = "analyzingAgency",
  AnalyticalMethod = "analyticalMethod",
  Projects = "projects",
  FromDate = "fromDate",
  ToDate = "toDate",
  CollectionMethod = "collectionMethod",
  QcSampleType = "qcSampleType",
  DataClassification = "dataClassification",
  SampleDepth = "sampleDepth",
  Units = "units",
  SpecimenId = "specimenId",
  LabBatchId = "labBatchId",
  LabArrivalFromDate = "labArrivalFromDate",
  LabArrivalToDate = "labArrivalToDate",
}
